Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('answer/', include('front.urls')),
    path('', include('main.urls')),
    path('api/', include('api.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from . import views
from django.urls import path

app_name = 'api'

urlpatterns = [
    path('quiz/', views.quiz_list, name='quiz-list'),
    path('question/', views.question_list, name='question-list'),
    path('answer/', views.answer_list, name='answer-list'),
    path('quiztaker/', views.quiztaker_list, name='quiztaker-list'),
]


              

front/urls.py
from django.urls import path
from . import views

app_name = 'front'

urlpatterns = [
    path('<str:code>', views.quiz_detail, name='quiz_detail'),
    path('answer/<str:code>', views.create_answers, name='create_answers'),
]

main/urls.py
from . import views
from django.urls import path

app_name = 'dash'

urlpatterns = [
    path('', views.main, name = 'main'),
    #quiz create
    path('create-quizz', views.create_quiz, name = 'quiz_create'),
    path('create-question/<int:id>', views.create_question , name ='quest_create' ),
    #quiz & questions detials
    path('questions/<int:id>', views.questions_list, name = 'questions'),
    path('question-detail/<int:id>', views.quest_detail, name = 'quest_detail'),
    path('quiz-delete/<int:id>', views.quiz_delete , name ='quiz_delete' ),
    path('get-results/<int:id>', views.get_results , name ='get_results' ),
    path('result-detail/<int:id>', views.result_detail , name ='result_detail' ),
    #auth
    path('login', views.logging_in, name = 'login'),
    path('register', views.register, name = 'register'),
    #export
    path('export/', views.export_results, name='export-results'),
]

main/models.py
import random, string


from django.db import models
from django.contrib.auth.models import User
from django_ckeditor_5.fields import CKEditor5Field

class Quiz(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=255, blank=True, unique=True)

    @property
    def all_questions(self):
        related = Question.objects.filter(quiz = self).count()
        return related

    def save(self, *args, **kwargs):
        if not self.id:
            self.code = "".join(
                random.sample(
                    string.ascii_letters, 
                    20
                )
            )
        super(Quiz, self).save(*args, **kwargs)

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    title = models.TextField()

    @property
    def correct_answer(self, *args, **kwargs):
        try:
            data = Option.objects.get(question_id=self.id, is_correct=True)   
        except:
            data = False
        return data

    @property
    def get_options(self, *args, **kwargs):
        options = list(Option.objects.filter(question_id=self.id))
        random.shuffle(options)
        return options

class Option(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    name = models.TextField()
    is_correct = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.pk:
            option = Option.objects.filter(question=self.question, is_correct=True)
            if option and self.is_correct:
                raise ValueError('Ikkita to`g`ri javob kiritish mumkin emas')
            elif not option and not self.is_correct :
                raise ValueError('Birinchi to`g`ri javob kiriting ')
        super(Option, self).save(*args, **kwargs)
    
    def __str__(self) -> str:
        return f"{self.question.title} = {self.name}"


class QuizTaker(models.Model):
    full_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    email = models.EmailField(blank=True, null=True)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)


class Answer(models.Model):
    taker = models.ForeignKey(QuizTaker, on_delete=models.DO_NOTHING)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.ForeignKey(Option, on_delete=models.CASCADE)
    is_correct = models.BooleanField()

    def save(self, *args, **kwargs):
        self.is_correct = self.answer == self.question.correct_answer
        super(Answer, self).save(*args, **kwargs)


class Result(models.Model):
    taker = models.ForeignKey(QuizTaker, on_delete=models.CASCADE)
    correct_answers = models.IntegerField()
    incorrect_answers = models.IntegerField()

    @property
    def questions(self, *args, **kwargs):
        quiz = self.taker.quiz
        result = Question.objects.filter(quiz=quiz).count()
        return result
    
    @property
    def percentage(self, *args, **kwargs):
        return self.correct_answers / self.questions * 100

main/views.py
from django.shortcuts import render, redirect
from .models import *
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import csv
from django.http import HttpResponse

# Create your views here.
@login_required(login_url = 'dash:login')
def main(request):
    quizes = Quiz.objects.filter(author = request.user)
    context = {
        "quizes" : quizes
    }
    return render(request, 'main.html', context)

@login_required(login_url = 'dash:login')
def create_quiz(request):
    if request.method == 'POST':
        title = request.POST['title']
        quiz = Quiz.objects.create(
            title = title,
            author = request.user
        )
        return redirect('dash:quest_create', quiz.id)
    return render(request, 'quiz/create-quiz.html')

#@login_required(login_url = 'dash:login')
#def create_question(request, id):
#    quiz = Quiz.objects.get(id = id)
#    if request.method == 'POST':
#        
#        title = request.POST['title']
#        ques = Question.objects.create(
#            quiz = quiz,
#            title = title
#        )
#        Option.objects.create(
#            question = ques,
#            name = request.POST['correct'],
#            is_correct = True
#        )
#        data = [request.POST['incorrect1'], request.POST['incorrect2'], request.POST['incorrect3']]
#
#        for i in data:
#            Option.objects.create(
#                question = ques,
#                name = i,
#            )
#        if request.POST['submit_action'] == 'exit':
#            return redirect('dash:main')
#
#    return render (request, 'quiz/create-question.html' )


@login_required(login_url='dash:login')
def create_question(request, id):
    quiz = Quiz.objects.get(id=id)
    if request.method == 'POST':
        title = request.POST.get('title', '')
        correct_answer = request.POST.get('correct', '')
        if title and correct_answer:
            # Create the question
            question = Question.objects.create(quiz=quiz, title=title)
            
            # Create the correct option
            Option.objects.create(question=question, name=correct_answer, is_correct=True)
            
            # Create incorrect options
            for i in range(1, 11):  # Assuming maximum 10 incorrect options
                incorrect_option = request.POST.get(f'incorrect{i}', '')
                if incorrect_option:
                    Option.objects.create(question=question, name=incorrect_option)
            
            if request.POST.get('submit_action') == 'exit':
                return redirect('dash:main')

    return render(request, 'quiz/create-question.html')



@login_required(login_url = 'dash:login')
def questions_list(request, id):
    quests = Question.objects.filter(quiz_id = id)
    context = {
        'questions': quests
    }
    return render (request, 'details/questions.html', context)

#@login_required(login_url = 'dash:login')
#def quest_detail(request, id):
#    question = Question.objects.get(id = id)
#    option_correct = Option.objects.get(question = question, is_correct = True)
#    options = Option.objects.filter(question = question, is_correct = False).order_by('id')
#    context = {
#        'question': question,
#        'options': options,
#        'option_correct' : option_correct
#    }
#    if request.method == 'POST':
#        question.title = request.POST['title']
#        question.save()
#
#        option_correct.name = request.POST['correct']
#        option_correct.save()
#
#        data = [request.POST['incorrect1'], request.POST['incorrect2'], request.POST['incorrect3']]
#
#        for i, opt in enumerate(options):
#            opt.name = data[i]
#            opt.save()
#    return render( request, 'details/detail.html', context)


@login_required(login_url='dash:login')
def quest_detail(request, id):
    question = Question.objects.get(id=id)
    option_correct = Option.objects.get(question=question, is_correct=True)
    options = Option.objects.filter(question=question, is_correct=False).order_by('id')
    context = {
        'question': question,
        'options': options,
        'option_correct': option_correct
    }
    if request.method == 'POST':
        title = request.POST.get('title', '')
        correct = request.POST.get('correct', '')
        incorrects = [request.POST.get(f'incorrect{i}', '') for i in range(1, 11)]  # 11 - Max incorrect answers
        if title:
            question.title = title
            question.save()
        if correct:
            option_correct.name = correct
            option_correct.save()
        for index, option in enumerate(options):
            if index < len(incorrects):
                incorrect = incorrects[index]
                if incorrect:
                    option.name = incorrect
                    option.save()
            else:
                break  # Stop iterating if there are no more incorrect answers provided
        if request.POST.get('submit_action') == 'exit':
            return redirect('dash:main')
    return render(request, 'details/detail.html', context)



@login_required(login_url = 'dash:login')
def quiz_delete(request, id):
    Quiz.objects.get(id = id).delete()
    return redirect('dash:main')



@login_required(login_url = 'dash:login')
def get_results(request, id):
    quiz = Quiz.objects.get(id=id)
    taker = QuizTaker.objects.filter(quiz=quiz)

    # results = []
    # for i in taker:
    #     results.append(Result.objects.get(taker=i))
    
    results = tuple(
            map(
            lambda x : Result.objects.get(taker=x),
            taker
        )
    )
    return render(request, 'quiz/results.html', {'results':results})

def result_detail(request, id):
    result = Result.objects.get(id=id)
    answers = Answer.objects.filter(taker=result.taker)
    context = {
        'taker':result.taker,
        'answers':answers
    }
    return render(request, 'quiz/result-detail.html', context)



#login


def logging_in(request):
    status = False
    if request.method == 'POST':
        username = request.POST['username']
        password =  request.POST['password']
        user = authenticate(username = username, password=password)
        if user:
            login(request, user)
            return redirect('dash:main')
        else:
            status = 'incorrect username or password'
    return render(request, 'auth/login.html', {'status':status})

def register(request):
    status = False
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if not User.objects.filter(username = username).first():
            User.objects.create_user(
                username=username,
                password=password
            )
            user = authenticate(username = username, password = password)
            login(request, user)
            return redirect('dash:main')
        else:
            status  = f'the username {username} is occupied'
    return render(request, 'auth/register.html', {'status': status})


#export excel


def export_results(request):
    results = Result.objects.all()

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="quiz_results.csv"'

    writer = csv.writer(response)
    writer.writerow(['FIO', 'Telefon', 'Email', 'Jami savollar', 'Togri javoblar', 'Notogri javoblar', 'Foiz'])

    for result in results:
        writer.writerow([
            result.taker.full_name,
            result.taker.phone,
            result.taker.email,
            result.questions,
            result.correct_answers,
            result.incorrect_answers,
            result.percentage
        ])

    return response

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">


<!-- index.html  21 Nov 2019 03:44:50 GMT -->
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>Otika - Admin Dashboard Template</title>
  <!-- General CSS Files -->
  <link rel="stylesheet" href="{% static 'assets/css/app.min.css' %}">
  <!-- Template CSS -->
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/components.css' %}">
  <!-- Custom style CSS -->
  <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
</head>

<body>
  <div class="loader"></div>
  <div id="app">
    <div class="main-wrapper main-wrapper-1">
      <div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar sticky">
        <div class="form-inline mr-auto">
          <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg
									collapse-btn"> <i data-feather="align-justify"></i></a></li>
            <li><a href="#" class="nav-link nav-link-lg fullscreen-btn">
                <i data-feather="maximize"></i>
              </a></li>
            <li>
              <form class="form-inline mr-auto">
                <div class="search-element">
                  <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="200">
                  <button class="btn" type="submit">
                    <i class="fas fa-search"></i>
                  </button>
                </div>
              </form>
            </li>
          </ul>
        </div>

      </nav>
      <div class="main-sidebar sidebar-style-2">
        <aside id="sidebar-wrapper">

          <ul class="sidebar-menu">
            <li class="dropdown active">
              <a href="{%url 'dash:main'%}" class="nav-link"><i data-feather="monitor"></i><span>Dashboard</span></a>
            </li>
            <li class="dropdown">
              <a href="#" class="menu-toggle nav-link has-dropdown"><i
                  data-feather="briefcase"></i><span>Quizes</span></a>
              <ul class="dropdown-menu">
                <li><a class="nav-link" href="{% url 'dash:quiz_create' %}">Create Quizz</a></li>
              </ul>
            </li>
          </ul>
        </aside>
      </div>
      <div class="main-content">
      {%block content%}
      
      {%endblock%}
        </div>
    </div>
</div>
<script src="https://kit.fontawesome.com/92b00ac3f6.js" crossorigin="anonymous"></script>
<!-- General JS Scripts -->
<script src="{% static 'assets/js/app.min.js'%}"></script>
<!-- JS Libraies -->
<script src="{% static 'assets/bundles/apexcharts/apexcharts.min.js'%}"></script>
<!-- Page Specific JS File -->
<script src="{% static 'assets/js/page/index.js'%}"></script>
<!-- Template JS File -->
<script src="{% static 'assets/js/scripts.js'%}"></script>
<!-- Custom JS File -->
<script src="{% static 'assets/js/custom.js'%}"></script>

</body>


<!-- index.html  21 Nov 2019 03:47:04 GMT -->
</html>

templates/main.html
{%extends 'base.html'%}
  {%block content%}
      <!-- Main Content -->

        <section class="section" >
          
          <div class="row d-flex justify-content-center">
            <h1 class="col-12" style="text-align: center;">All quizes you've created</h1>
          {% for quiz in quizes %}
         
          <div class="card card-danger col-5 m-2">
            <div class="card-header">
              <h4>{{quiz.title}}</h4>
              <div class="card-header-action">
                <a href="{%url 'dash:questions' quiz.id%}" class="btn btn-primary">View the quiz</a>
                <div class="dropdown">
                  <a href="{%url 'dash:quiz_delete' quiz.id%}" class="btn btn-danger">Delete quiz</a>
                </div>
              </div>
            </div>
            <div class="card-body">
            </div>
            <p>Contains {{quiz.all_questions}} question(s) overall</p>
            <script>
              function copyUrl() {
                  var url = "{% url 'front:quiz_detail' quiz.code %}";
                  // URLni olish
                  var dummy = document.createElement("input");
                  document.body.appendChild(dummy);
                  dummy.setAttribute('value', url);
                  dummy.select();
                  document.execCommand("copy");
                  document.body.removeChild(dummy);
                  // Foydalanuvchiga ko'rsatish
                  alert("URL nusxalandi: " + url);
              }
          </script>
          
          <button onclick="copyUrl()">Linkni Nusxalash</button>
            <h4><a href="{% url 'front:quiz_detail' quiz.code %}">link</a></h4>
            <h4><a href="{% url 'dash:get_results' quiz.id %}">Results</a>
            </div>

          {%endfor%}
        </div>
        </section>
        <div class="settingSidebar">
          <a href="javascript:void(0)" class="settingPanelToggle"> <i class="fa fa-spin fa-cog"></i>
          </a>
          <div class="settingSidebar-body ps-container ps-theme-default">
            <div class=" fade show active">
              <div class="setting-panel-header">Setting Panel
              </div>
              <div class="p-15 border-bottom">
                <h6 class="font-medium m-b-10">Select Layout</h6>
                <div class="selectgroup layout-color w-50">
                  <label class="selectgroup-item">
                    <input type="radio" name="value" value="1" class="selectgroup-input-radio select-layout" checked>
                    <span class="selectgroup-button">Light</span>
                  </label>
                  <label class="selectgroup-item">
                    <input type="radio" name="value" value="2" class="selectgroup-input-radio select-layout">
                    <span class="selectgroup-button">Dark</span>
                  </label>
                </div>
              </div>
              <div class="p-15 border-bottom">
                <h6 class="font-medium m-b-10">Sidebar Color</h6>
                <div class="selectgroup selectgroup-pills sidebar-color">
                  <label class="selectgroup-item">
                    <input type="radio" name="icon-input" value="1" class="selectgroup-input select-sidebar">
                    <span class="selectgroup-button selectgroup-button-icon" data-toggle="tooltip"
                      data-original-title="Light Sidebar"><i class="fas fa-sun"></i></span>
                  </label>
                  <label class="selectgroup-item">
                    <input type="radio" name="icon-input" value="2" class="selectgroup-input select-sidebar" checked>
                    <span class="selectgroup-button selectgroup-button-icon" data-toggle="tooltip"
                      data-original-title="Dark Sidebar"><i class="fas fa-moon"></i></span>
                  </label>
                </div>
              </div>
              <div class="p-15 border-bottom">
                <h6 class="font-medium m-b-10">Color Theme</h6>
                <div class="theme-setting-options">
                  <ul class="choose-theme list-unstyled mb-0">
                    <li title="white" class="active">
                      <div class="white"></div>
                    </li>
                    <li title="cyan">
                      <div class="cyan"></div>
                    </li>
                    <li title="black">
                      <div class="black"></div>
                    </li>
                    <li title="purple">
                      <div class="purple"></div>
                    </li>
                    <li title="orange">
                      <div class="orange"></div>
                    </li>
                    <li title="green">
                      <div class="green"></div>
                    </li>
                    <li title="red">
                      <div class="red"></div>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="p-15 border-bottom">
                <div class="theme-setting-options">
                  <label class="m-b-0">
                    <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input"
                      id="mini_sidebar_setting">
                    <span class="custom-switch-indicator"></span>
                    <span class="control-label p-l-10">Mini Sidebar</span>
                  </label>
                </div>
              </div>
              <div class="p-15 border-bottom">
                <div class="theme-setting-options">
                  <label class="m-b-0">
                    <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input"
                      id="sticky_header_setting">
                    <span class="custom-switch-indicator"></span>
                    <span class="control-label p-l-10">Sticky Header</span>
                  </label>
                </div>
              </div>
              <div class="mt-4 mb-4 p-3 align-center rt-sidebar-last-ele">
                <a href="#" class="btn btn-icon icon-left btn-primary btn-restore-theme">
                  <i class="fas fa-undo"></i> Restore Default
                </a>
              </div>
            </div>
          </div>
        </div>

  {%endblock%}